#pragma kernel CSMain

struct InstanceData
{
    float3 position;
};

RWStructuredBuffer<InstanceData> instanceBuffer;
float deltaTime;

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float time = id.x * 0.1 + deltaTime;
    instanceBuffer[id.x].position.x += cos(time) * 0.3;
    instanceBuffer[id.y].position.y += sin(time) * 0.3;
    instanceBuffer[id.z].position.z += sin(time * 0.2);
}